### PR TITLE
Update programme.md

### PR DESCRIPTION
**Pull request by nevrome**
### PR Checklist:

* [ ] Have you rendered and checked the website after your modifications with [docsify-cli](https://docsify.js.org/#/quickstart) ?
* [x] Have you updated the `docs/_sidebar.md` file if you added new markdown files ?

Feel free to adjust the layout. I didn't render anything.

### CODE REVIEW

**Comment by nevrome** [comment]
@alexhbnr Is this what you had in mind?

**Review by alexhbnr — APPROVED** [review]

**Review by alexhbnr — APPROVED** [review]

**Comment by maxibor** [comment]
@nevrome you can merge the PR ;)

**Comment by nevrome** [comment]
image

Nope ¯\\_(ツ)_/¯

**Comment by nevrome** [comment]
Maybe you remove these restrictions. IMHO we can trust each other enough :+1:

**Review by maxibor — APPROVED** [review]

**Pull request merged**
